//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_good_links
    {
        public int link_id { get; set; }
        public int good_id { get; set; }
        public int material_id { get; set; }
        public decimal quantity { get; set; }
    
        public virtual good good { get; set; }
        public virtual material material { get; set; }
    }
}
