//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transaction_id { get; set; }
        public int tran_order_id { get; set; }
        public int transaction_type_id { get; set; }
        public int employee_id { get; set; }
        public int material_id { get; set; }
        public int provider_id { get; set; }
        public int quantity { get; set; }
        public decimal transaction_sum { get; set; }
        public System.DateTime transaction_date { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual material material { get; set; }
        public virtual provider provider { get; set; }
        public virtual transaction_types transaction_types { get; set; }
    }
}
